version: '2'
services:
  homeless-service:
    environment:
    - PROJ_SETTINGS_DIR=${PROJ_SETTINGS_DIR}
    - DEPLOY_TARGET=${DEPLOY_TARGET}
    - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    - CONFIG_BUCKET=${CONFIG_BUCKET}
    - DATABASE_NAME=${DATABASE_NAME}
    - DATABASE_HOST=${DATABASE_HOST}
    - DATABASE_USER=${DATABASE_USER}
    - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    - DATABASE_PORT=${DATABASE_PORT}
    - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
    
    build: .
    image: "${DOCKER_REPO}/${DOCKER_IMAGE}"
    command: ./code/bin/docker-entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
